### ISSUE TITLE
SMB3 Support

### ISSUE THREAD

**Issue by primalglenn** [vmware/likewise-open#22]
I operate in a secure environment and our Windows Domain Controllers have been enabled for SMB Encryption (See: https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-security). This appears to be part of the SMB 3 protocol which doesn't appear to be supported by likewise open. The VMware VCSA appliance which runs on photon OS from what I can tell is using likewise-open for active directory integration and as such when trying to join the appliance to an AD domain (./domainjoin-cli --loglevel verbose join --ou OU_here Account_here) it fails when SMB encryption is enabled (on the domain controllers. For reference this is the powershell cmdlet "Set-SmbServerConfiguration -EncryptData $true -RejectUnencryptedAccess $true"). The specific error that it throws when establishing an SMB session is "NT Status: STATUS_ACCESS_DENIED (0xc0000022)". 

I tested in a Lab environment and confirmed that disabling SMB encryption allows the appliance to join AD and function properly. Unfortunately, in my production environment it is not feasible for me to disable this setting (due to security reasons). Are there any plans for adding SMB 3 support to likewise open? Apologies if this isn't the right place for this but I logged a VMware case (SR#19088345812) and didn't get far with the first level of support. Thanks!

Regards,

Glenn

**Comment by ssalley** [comment]
Glenn, We will follow up on the VMware case separately. Likewise Open is an independent open source project for which we will have to evaluate SMB3 support.

**Comment by primalglenn** [comment]
Hi Scott,

Thanks for the reply and for your consideration in evaluating SMB3 support.

Regards,

Glenn

**Comment by emaste** [comment]
I presume "completed" is not accurate for the resolution, and there are no current plans to implement SMBv3 support?
